spring:
  application:
    name: km124-api
  datasource:
    url: jdbc:postgresql://localhost:5432/km124-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true